name: ugrip-energy-a2c
program: train_a2c.py
method: bayes
metric:
  goal: maximize
  name: rollout/ep_rew_mean
parameters:
  learning_rate:
    min: 0.0003
    max: 0.003
  gamma:
    min: 0.9
    max: 0.99
  vf_coef:
    min: 0.1
    max: 1
  qf_nns:
    values: [64, 128, 256, 512]
  pi_nns:
    values: [64, 128, 256, 512]