name: ugrip-energy
program: train_ppo.py
method: random
metric:
  goal: maximize
  name: rollout/ep_rew_mean
parameters:
  learning_rate:
    min: 0.0003
    max: 0.003
  n_epochs:
    values: [5, 10, 20]
  gamma:
    min: 0.9
    max: 0.99
  clip_range:
    min: 0.1
    max: 0.3
  use_sde:
    values: [True, False]
  vf_nns:
    values: [32, 64, 128]
  pi_nns:
    values: [32, 64, 128]