name: ugrip-energy-td3
project: ugrip
entity: optimllab
program: train_scripts/td3.py
method: bayes
metric:
  goal: maximize
  name: rollout/ep_rew_mean
parameters:
  learning_rate:
    min: 0.0003
    max: 0.003
  gamma:
    min: 0.9
    max: 0.99
  tau:
    min: 0.001
    max: 0.01
  target_policy_noise:
    min: 0.1
    max: 0.3
  qf_nns:
    values: [64, 128, 256, 512]
  pi_nns:
    values: [64, 128, 256, 512]